name: madrasa_app
description: رابط أعضاء المدرسة القرآنية بمدير المالية ومدير الصيانة
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.4
  cloud_firestore: ^6.6.0
  firebase_storage: ^13.4.3
  image_picker: ^1.1.2
  cloudinary_flutter: ^1.1.0
  cloudinary_url_gen: ^1.1.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  firebase_messaging: ^16.4.1
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
